/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-06-19 09:13:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginafter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("            .userMenu {\r\n");
      out.write("                float: left;\r\n");
      out.write("                width: 200px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            #content {\r\n");
      out.write("                float: left;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <script src=\"http://code.jquery.com/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"userWrap\">\r\n");
      out.write("            <ul class=\"userMenu\">\r\n");
      out.write("                <li class=\"current\" data-id=\"center\">用户中心</li>\r\n");
      out.write("                <li data-id=\"likai\">离校申请</li>\r\n");
      out.write("                <li data-id=\"huilai\">返校处理</li>\r\n");
      out.write("                 <li data-id=\"xiugai\">修改密码</li>\r\n");
      out.write("          \r\n");
      out.write("            </ul>\r\n");
      out.write("            <div id=\"content\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("        $(function() {\r\n");
      out.write("            $(\".userMenu\").on(\"click\", \"li\", function() {\r\n");
      out.write("                var sId = $(this).data(\"id\"); //获取data-id的值\r\n");
      out.write("                window.location.hash = sId; //设置锚点\r\n");
      out.write("                loadInner(sId);\r\n");
      out.write("            });\r\n");
      out.write("            function loadInner(sId) {\r\n");
      out.write("                var sId = window.location.hash;\r\n");
      out.write("                var pathn, i;\r\n");
      out.write("                switch(sId) {\r\n");
      out.write("                    case \"#center\":\r\n");
      out.write("                        pathn = \"user_center.jsp\";\r\n");
      out.write("                        i = 0;\r\n");
      out.write("                        break;\r\n");
      out.write("                    case \"#likai\":\r\n");
      out.write("                        pathn = \"user_likai.jsp\";\r\n");
      out.write("                        i = 1;\r\n");
      out.write("                        break;\r\n");
      out.write("                        \r\n");
      out.write("                    case \"#huilai\":\r\n");
      out.write("                        pathn = \"user_huilai.jsp\";\r\n");
      out.write("                        i = 2;\r\n");
      out.write("                        break;\r\n");
      out.write("\r\n");
      out.write("                    case \"#xiugai\":\r\n");
      out.write("                        pathn = \"user_xiugai.jsp\";\r\n");
      out.write("                        i = 3;\r\n");
      out.write("                        break;\r\n");
      out.write("                        \r\n");
      out.write("                    default:\r\n");
      out.write("                        pathn = \"user_center.jsp\";\r\n");
      out.write("                        i = 0;\r\n");
      out.write("                        break;\r\n");
      out.write("                }\r\n");
      out.write("                $(\"#content\").load(pathn); //加载相对应的内容\r\n");
      out.write("                $(\".userMenu li\").eq(i).addClass(\"current\").siblings().removeClass(\"current\"); //当前列表高亮\r\n");
      out.write("            }\r\n");
      out.write("            var sId = window.location.hash;\r\n");
      out.write("            loadInner(sId);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
